# Generated by Django 3.2.8 on 2021-11-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='idTransacoes',
        ),
    ]
