# Generated by Django 3.2.8 on 2021-11-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0002_remove_categorias_idtransacoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
