# Generated by Django 3.2.8 on 2021-11-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0003_delete_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transations',
            name='idCategorias',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='transations.categorias'),
        ),
    ]
