# Generated by Django 3.2.9 on 2021-11-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0004_transations_idcategorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transations',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
