# Generated by Django 3.2.9 on 2021-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_email_user_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=68),
        ),
    ]
